"""Add cascade delete to reservations

Revision ID: 353cc2c10456
Revises: 835eae99980f
Create Date: 2025-04-09 22:19:59.818315

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "353cc2c10456"
down_revision: Union[str, None] = "835eae99980f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("reservations_table_id_fkey", "reservations", type_="foreignkey")
    op.create_foreign_key(
        None, "reservations", "tables", ["table_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reservations", type_="foreignkey")
    op.create_foreign_key(
        "reservations_table_id_fkey", "reservations", "tables", ["table_id"], ["id"]
    )
    # ### end Alembic commands ###
